#import "./fragments/cart.gql"
#import "./fragments/errors.gql"

# Create a new checkout
mutation cartCreate(
	$input: CartInput
	$includeCustomer: Boolean = false
	$country: CountryCode
	$language: LanguageCode)
	@inContext(country: $country, language: $language) {

	mutation: cartCreate(input: $input) {
		cart { ...cart }
		userErrors { ...cartUserError }
	}
}
