#import "./fragments/cart.gql"
#import "./fragments/errors.gql"

# Create a new checkout
mutation cartCreate(
	$input: CartInput
	$includeCustomer: Boolean = false) {

	mutation: cartCreate(input: $input) {
		cart { ...cart }
		userErrors { ...cartUserError }
	}
}
