#import "./fragments/cart.gql"
#import "./fragments/errors.gql"

# Update a line item
mutation cartBuyerIdentityUpdate (
	$cartId: ID!
	$buyerIdentity: CartBuyerIdentityInput!
	$includeCustomer: Boolean = true
	$country: CountryCode
	$language: LanguageCode)
	@inContext(country: $country, language: $language) {

  mutation: cartBuyerIdentityUpdate(
		cartId: $cartId
		buyerIdentity: $buyerIdentity) {

		cart { ...cart }
		userErrors { ...cartUserError }

	}
}
