#import "./price.gql"
#import "./product.gql"
#import "./variant.gql"

# All the data needed to represent the cart in the UI
fragment cart on Cart {
	id
	checkoutUrl

	# Customer info
	buyerIdentity @include(if: $includeCustomer) {
		customer { id }
	}

	# Order value
	cost {
		subtotalAmount { ...price }
		totalAmount { ...price }
		totalTaxAmount { ...price }
	}

	# List of discount codes
	discountCodes {
		applicable
		code
	}

	# The list of line items
	lines (first: 100) {
		edges {
			cursor
			node { ...cartLine }
		}
	}
}

# The line of the cart
fragment cartLine on CartLine {
	id
	quantity
	variant: merchandise {
		...variant
		... on ProductVariant {
			product { ...product }
		}
	}
	cost {
		subtotalAmount { ...price }
		totalAmount { ...price }
	}
	sellingPlanAllocation { ...sellingPlanAllocation }
	attributes { key, value }
}
