#import "./image.gql"
#import "./variant.gql"

# Product data, primarily concerned with rendering a product in lists.  Like
# it includes variant info but lacks product description. I am naming this
# generically ("product" rather than "product-card") because I want to
# encourage using only this fragment when fetching product data so we can
# depend on a consistent payload object structure.
fragment product on Product {
	id
	handle
	title
	tags

	# Heirarchy
	productType
	vendor

	# Availalability
	onlineStoreUrl
	availableForSale

	# Variant options
	options {
		name
		values
	}

	# List of variants
	variants(first:100) {
		edges {
			node { ...variant }
		}
	}

	# Get more images than needed because this fragment is also used on PDP
	images(first:10) {
		edges {
			node { ...image }
		}
	}
}
